In [1]:
import pandas as pd

In [7]:
partner_headlines = pd.read_csv("raw/raw_partner_headlines.csv")
partner_headlines.head()

,Unnamed: 0,headline,url,publisher,date,stock
0,2,Agilent Technologies Announces Pricing of $5……...,http://www.gurufocus.com/news/1153187/agilent-...,GuruFocus,2020-06-01 00:00:00,A
1,3,Agilent (A) Gears Up for Q2 Earnings: What's i...,http://www.zacks.com/stock/news/931205/agilent...,Zacks,2020-05-18 00:00:00,A
2,4,J.P. Morgan Asset Management Announces Liquida...,http://www.gurufocus.com/news/1138923/jp-morga...,GuruFocus,2020-05-15 00:00:00,A
3,5,"Pershing Square Capital Management, L.P. Buys ...",http://www.gurufocus.com/news/1138704/pershing...,GuruFocus,2020-05-15 00:00:00,A
4,6,Agilent Awards Trilogy Sciences with a Golden ...,http://www.gurufocus.com/news/1134012/agilent-...,GuruFocus,2020-05-12 00:00:00,A

In [8]:
print(sum(partner_headlines["headline"].isna()))
print(sum(partner_headlines["date"].isna()))
print(sum(partner_headlines["stock"].isna()))

0
0
0

No hay ninguna columna que nos interese con NAs, por lo que simplemente nos quedamos con las columnas *headline*, *date* y *stock*, corregimos la columna *Unnamed: 0*, le cambiamos el nombre a *index* y se la asignamos al índice del dataframe.

In [9]:
partner_headlines["index"] = list(range(len(partner_headlines)))
partner_headlines = partner_headlines[["index", "headline", "date", "stock"]]
partner_headlines = partner_headlines.set_index("index")

In [10]:
partner_headlines

,headline,date,stock
index,,,
0,Agilent Technologies Announces Pricing of $5……...,2020-06-01 00:00:00,A
1,Agilent (A) Gears Up for Q2 Earnings: What's i...,2020-05-18 00:00:00,A
2,J.P. Morgan Asset Management Announces Liquida...,2020-05-15 00:00:00,A
3,"Pershing Square Capital Management, L.P. Buys ...",2020-05-15 00:00:00,A
4,Agilent Awards Trilogy Sciences with a Golden ...,2020-05-12 00:00:00,A
...,...,...,...
1845554,Consumer Cyclical Sector Wrap,2012-08-20 00:00:00,ZX
1845555,Consumer Cyclical Sector Wrap,2012-07-23 00:00:00,ZX
1845556,Zacks #5 Rank Additions for Monday - Tale of t...,2012-04-23 00:00:00,ZX
1845557,4 Stock Strategies From Wall Street: Feb. 9 (U...,2012-02-09 00:00:00,ZX
1845558,4 Stock Strategies From Wall Street: Feb. 9,2012-02-09 00:00:00,ZX

In [17]:
partner_headlines.iloc[:len(partner_headlines)//2,].to_csv("processed/partner_headlines_cleaned-1.csv")
partner_headlines.iloc[len(partner_headlines)//2:,].to_csv("processed/partner_headlines_cleaned-2.csv")

In [19]:
pd.read_csv("processed/partner_headlines_cleaned-1.csv").head()

,index,headline,date,stock
0,0,Agilent Technologies Announces Pricing of $5……...,2020-06-01 00:00:00,A
1,1,Agilent (A) Gears Up for Q2 Earnings: What's i...,2020-05-18 00:00:00,A
2,2,J.P. Morgan Asset Management Announces Liquida...,2020-05-15 00:00:00,A
3,3,"Pershing Square Capital Management, L.P. Buys ...",2020-05-15 00:00:00,A
4,4,Agilent Awards Trilogy Sciences with a Golden ...,2020-05-12 00:00:00,A

In [20]:
pd.read_csv("processed/partner_headlines_cleaned-2.csv").head()

,index,headline,date,stock
0,922779,New tariff threat runs ramshod over apparel/fo...,2019-08-01 00:00:00,JWN
1,922780,Nordstrom jumps 10% on report family exploring...,2019-07-31 00:00:00,JWN
2,922781,Apparel chains in harm's way from Amazon shopp...,2019-07-30 00:00:00,JWN
3,922782,Hot 90 S&P 500 Dividend Dogs Strut Their Stuff...,2019-07-23 00:00:00,JWN
4,922783,Dillard's: A Friday Afternoon Spike Puts It On...,2019-07-22 00:00:00,JWN